### ISSUE TITLE
ECDSA signature verification failure

### ISSUE THREAD

**Issue by ROTGP** [rubo/flame#6]
I couldn't find any test-cases or examples with your ECDSA code, so maybe I'm missing something, but I don't think so.  The code below produces an invalid signature (even though it uses the same ECDSA instance for signature and verification, supposedly using the private/public keypair generated when the object is instantiated).  I've tried compiling from the source code, and using the SWC as well - same result.  RSA works fine.

var ba:ByteArray = new ByteArray();
ba.writeUTF("testing123");

var sha256:SHA256 = new SHA256();

var hash:ByteArray = sha256.computeHash(ba);

var ecdsa:ECDSA = new ECDSA(256);

var signature:ByteArray = ecdsa.signHash(hash);

var valid:Boolean = ecdsa.verifyHash(hash, signature);

trace('signature valid: ' + valid);  // signature valid: false

**Comment by rubo** [comment]
Nice catch, thank you. That's what happens when there are no test cases. The SWC is also updated.
I'd recommend you not to use the ECDSA class directly. For signing operation use the ECDSASignatureFormatter class and for the verification operation use the ECDSASignatureDeformatter class. Thus, your code above transforms to:

``` actionscript
var ba:ByteArray = new ByteArray();
ba.writeUTF("testing123");

var ecdsa:ECDSA = new ECDSA(256);

var formatter:ECDSASignatureFormatter = new ECDSASignatureFormatter(ecdsa);
formatter.setHashAlgorithm("SHA-256");

var signature:ByteArray = formatter.createSignature(ba);

var deformatter:ECDSASignatureDeformatter = new ECDSASignatureDeformatter(ecdsa);
deformatter.setHashAlgorithm("SHA-256");

var valid:Boolean = deformatter.verifySignature(ba, signature);

trace("signature valid:", valid);
```

For the supported names of available hash algorithms, please refer to the CrytpoConfig class docs.
